In [7]:
import requests 
import json
import pandas as pd

In [8]:
url = "https://chronicdata.cdc.gov/resource/rb39-ixr6.json"

In [9]:
print(requests.get(url))

<Response [200]>

In [10]:
#print(requests.get(url).json())

In [11]:
response = requests.get(url).json()
#print(json.dumps(response, indent = 4, sort_keys=True))

In [12]:
healthdata = pd.DataFrame(response)
healthdata.head()

,:@computed_region_bxsw_vy29,:@computed_region_he4y_prf8,age,data_value,data_value_footnote,data_value_footnote_symbol,data_value_std_err,data_value_type,data_value_unit,datasource,...,stratificationid2,stratificationid3,stratificationid4,submeasure,submeasureid,topicdesc,topicid,topictype,topictypeid,year
0,17,1287,All Ages,39.5,NaN,NaN,2.4,Percentage,%,YRBSS,...,8AGE,5RAC,2EDU,Ever Cigarette Smoker,YRB03,Cigarette Use (Youth),106BEH,Tobacco Use - Survey Data,BEH,2011
1,14,3084,All Ages,34.6,NaN,NaN,2.2,Percentage,%,YRBSS,...,8AGE,6RAC,2EDU,Current Cigarette Smoker,YRB01,Cigarette Use (Youth),106BEH,Tobacco Use - Survey Data,BEH,1999
2,43,1046,All Ages,8.3,NaN,NaN,0.8,Percentage,%,YRBSS,...,8AGE,6RAC,1EDU,Current Cigarette Smoker,YRB01,Cigarette Use (Youth),106BEH,Tobacco Use - Survey Data,BEH,2009
3,14,3084,All Ages,19.6,NaN,NaN,1.5,Percentage,%,YRBSS,...,8AGE,6RAC,2EDU,Frequent Cigarette Smoker,YRB02,Cigarette Use (Youth),106BEH,Tobacco Use - Survey Data,BEH,1995
4,14,3084,All Ages,4.9,NaN,NaN,0.5,Percentage,%,YRBSS,...,8AGE,5RAC,2EDU,Frequent Smokeless Tobacco User,YRB05,Smokeless Tobacco Use (Youth),151BEH,Tobacco Use - Survey Data,BEH,2013

In [14]:
#Collecting a list of all columns within the DataFrame
healthdata.columns

Index([':@computed_region_bxsw_vy29', ':@computed_region_he4y_prf8', 'age',
       'data_value', 'data_value_footnote', 'data_value_footnote_symbol',
       'data_value_std_err', 'data_value_type', 'data_value_unit',
       'datasource', 'displayorder', 'education', 'gender', 'geolocation',
       'high_confidence_limit', 'locationabbr', 'locationdesc',
       'low_confidence_limit', 'measuredesc', 'measureid', 'race', 'response',
       'sample_size', 'stratificationid1', 'stratificationid2',
       'stratificationid3', 'stratificationid4', 'submeasure', 'submeasureid',
       'topicdesc', 'topicid', 'topictype', 'topictypeid', 'year'],
      dtype='object')

In [16]:
# Reorganizing the columns using double brackets
organized_df = healthdata[["year", "locationabbr", "topicdesc", "response", "data_value", "gender", "race","education", "stratificationid1", "stratificationid2", "stratificationid3", "stratificationid4"]]
organized_df.head()

,year,locationabbr,topicdesc,response,data_value,gender,race,education,stratificationid1,stratificationid2,stratificationid3,stratificationid4
0,2011,KS,Cigarette Use (Youth),Ever,39.5,Overall,White,High School,1GEN,8AGE,5RAC,2EDU
1,1999,WY,Cigarette Use (Youth),Current,34.6,Male,All Races,High School,2GEN,8AGE,6RAC,2EDU
2,2009,DE,Cigarette Use (Youth),Current,8.3,Female,All Races,Middle School,3GEN,8AGE,6RAC,1EDU
3,1995,WY,Cigarette Use (Youth),Frequent,19.6,Female,All Races,High School,3GEN,8AGE,6RAC,2EDU
4,2013,WY,Smokeless Tobacco Use (Youth),Frequent,4.9,Overall,White,High School,1GEN,8AGE,5RAC,2EDU

In [17]:
renamed_df = organized_df.rename(columns={"locationabbr":"State", "topicdesc":"Use Type", "response":"Use Frequency", "data_value":"% of Respondents"})
renamed_df.head()

,year,State,Use Type,Use Frequency,% of Respondents,gender,race,education,stratificationid1,stratificationid2,stratificationid3,stratificationid4
0,2011,KS,Cigarette Use (Youth),Ever,39.5,Overall,White,High School,1GEN,8AGE,5RAC,2EDU
1,1999,WY,Cigarette Use (Youth),Current,34.6,Male,All Races,High School,2GEN,8AGE,6RAC,2EDU
2,2009,DE,Cigarette Use (Youth),Current,8.3,Female,All Races,Middle School,3GEN,8AGE,6RAC,1EDU
3,1995,WY,Cigarette Use (Youth),Frequent,19.6,Female,All Races,High School,3GEN,8AGE,6RAC,2EDU
4,2013,WY,Smokeless Tobacco Use (Youth),Frequent,4.9,Overall,White,High School,1GEN,8AGE,5RAC,2EDU