In [14]:
import requests 
import json
import pandas as pd

In [15]:
url = "https://chronicdata.cdc.gov/resource/rb39-ixr6.json"

In [16]:
print(requests.get(url))

<Response [200]>

In [17]:
#print(requests.get(url).json())

In [18]:
response = requests.get(url).json()
#print(json.dumps(response, indent = 4, sort_keys=True))

In [19]:
health_df = pd.DataFrame(response)
health_df.head()

,:@computed_region_bxsw_vy29,:@computed_region_he4y_prf8,age,data_value,data_value_footnote,data_value_footnote_symbol,data_value_std_err,data_value_type,data_value_unit,datasource,...,stratificationid2,stratificationid3,stratificationid4,submeasure,submeasureid,topicdesc,topicid,topictype,topictypeid,year
0,17,1287,All Ages,39.5,NaN,NaN,2.4,Percentage,%,YRBSS,...,8AGE,5RAC,2EDU,Ever Cigarette Smoker,YRB03,Cigarette Use (Youth),106BEH,Tobacco Use - Survey Data,BEH,2011
1,14,3084,All Ages,34.6,NaN,NaN,2.2,Percentage,%,YRBSS,...,8AGE,6RAC,2EDU,Current Cigarette Smoker,YRB01,Cigarette Use (Youth),106BEH,Tobacco Use - Survey Data,BEH,1999
2,43,1046,All Ages,8.3,NaN,NaN,0.8,Percentage,%,YRBSS,...,8AGE,6RAC,1EDU,Current Cigarette Smoker,YRB01,Cigarette Use (Youth),106BEH,Tobacco Use - Survey Data,BEH,2009
3,14,3084,All Ages,19.6,NaN,NaN,1.5,Percentage,%,YRBSS,...,8AGE,6RAC,2EDU,Frequent Cigarette Smoker,YRB02,Cigarette Use (Youth),106BEH,Tobacco Use - Survey Data,BEH,1995
4,14,3084,All Ages,4.9,NaN,NaN,0.5,Percentage,%,YRBSS,...,8AGE,5RAC,2EDU,Frequent Smokeless Tobacco User,YRB05,Smokeless Tobacco Use (Youth),151BEH,Tobacco Use - Survey Data,BEH,2013

In [ ]:
#Collecting a list of all columns within the DataFrame
health_df.columns

In [ ]:
# Reorganizing the columns using double brackets
organized_df = health_df[["YEAR", "LocationAbbr", "TopicDesc", "Response", "Data_Value", "Gender", "Race","Education", "StratificationID1", "StratificationID2", "StratificationID3", "StratificationID4"]]
organized_df.head()

In [ ]:
renamed_df = organized_df.rename(columns={"LocationAbbr":"State", "TopicDesc":"Use Type", "Response":"Use Frequency", "Data_Value":"% of Respondents"})
renamed_df.head()